server:
  port: 8090  # 9000? ??? ??

spring:
  datasource:
    platform: mysql
    url: jdbc:mysql://umc-first-db.cru8xjfbbqxz.ap-northeast-2.rds.amazonaws.com:3306/umc_carrot_market?serverTimezone=Asia/Seoul
    # url ??? jdbc:mysql://RDS? EndPoint/?? DB ???? ???.
    username: master # ?? ?? ???? ????? ???? admin ???
    password: mysqlmj** # ????? ??????!
    driver-class-name: com.mysql.cj.jdbc.Driver
