server:
  port: 8090

spring:
  datasource:
    platform: mysql
    url: jdbc:mysql://umc-first-db.cru8xjfbbqxz.ap-northeast-2.rds.amazonaws.com:3306/umc_carrot_market?serverTimezone=Asia/Seoul
    username: master
    password: mysqlmj**
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    show-sql: true
    hibernate:
      format_sql: true
      ddl-auto: none
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl